app.py
from config import ADMIN_PASSWORD
from infrastructure.blog import blogmain
import urllib
from flask import (Flask, abort, flash, Markup, redirect, render_template,
                   request, Response, session, url_for)
from flask_simplemde import SimpleMDE

app = Flask(__name__)
app.config.from_pyfile('config.py')
SimpleMDE(app)


def main():
    register_blueprints()
    blogmain()
    app.run(debug=True)


def register_blueprints():
    from views import home_views, blog_views, capstone_views

    app.register_blueprint(home_views.blueprint)
    app.register_blueprint(capstone_views.blueprint)
    app.register_blueprint(blog_views.blueprint)


# TODO: Fix blog?


def login():
    if request.method == 'POST' and request.form.get('password'):
        password = request.form.get('password')
        if password == ADMIN_PASSWORD:
            session['logged_in'] = True
            session.permanent = True  # Use cookie to store session.
            flash('You are now logged in.', 'success')
            loginstate = True
            print('password match and returning loginstate ', loginstate)
            return loginstate
        else:
            flash('Incorrect password.', 'danger')
            loginstate = False
            return loginstate


@app.template_filter('clean_querystring')
def clean_querystring(request_args, *keys_to_remove, **new_values):
    querystring = dict((key, value) for key, value in request_args.items())
    for key in keys_to_remove:
        querystring.pop(key, None)
    querystring.update(new_values)
    return urllib.urlencode(querystring)


"""
@app.errorhandler(404)
def not_found(exc):
    return Response('<h3>Not found</h3>'), 404
"""

if __name__ == '__main__':
    main()
else:
    register_blueprints()

views/blog_views.py
import functools

import flask
from flask import (flash, redirect, render_template,
                   request, session, url_for)
from playhouse.flask_utils import get_object_or_404, object_list

from infrastructure.blog import Entry
from infrastructure.view_modifiers import response

blueprint = flask.Blueprint('blog', __name__, template_folder='templates')



@blueprint.route('/blog')
def blog():
    search_query = request.args.get('q')
    if search_query:
        query = Entry.search(search_query)
    else:
        query = Entry.public().order_by(Entry.timestamp.desc())
        print(query)
    return object_list('blog/index.html', query, search=search_query)


@blueprint.route('/blog/post')
@response(template_file='blog/post.html')
def post():
    return {}


@blueprint.route('/blog/post/<title>')
@response(template_file='blog/post.html')
def post_title():
    return {}


def login_required(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if session.get('logged_in'):
            return fn(*args, **kwargs)
        return redirect(url_for('blog/login', next=request.path))

    return inner


@blueprint.route('/drafts/')
@login_required
def drafts():
    query = Entry.drafts().order_by(Entry.timestamp.desc())
    return object_list('blog/index.html', query)


@blueprint.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        if request.form.get('title') and request.form.get('content'):
            entry = Entry.create(
                title=request.form['title'],
                content=request.form['content'],
                published=request.form.get('published') or False)
            flash('Entry created successfully.', 'success')
            if entry.published:
                print(entry.slug)
                return redirect(url_for('blog.detail', slug=entry.slug))
            else:
                return redirect(url_for('blog.edit', slug=entry.slug))
        else:
            flash('Title and Content are required.', 'danger')
    return render_template('blog/create.html')


@blueprint.route('/<slug>/')
def detail(slug):
    if session.get('logged_in'):
        query = Entry.select()
    else:
        query = Entry.public()
    entry = get_object_or_404(query, Entry.slug == slug)
    return render_template('blog/post.html', entry=entry)


@blueprint.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit(slug):
    entry = get_object_or_404(Entry, Entry.slug == slug)
    if request.method == 'POST':
        if request.form.get('title') and request.form.get('content'):
            entry.title = request.form['title']
            entry.content = request.form['content']
            entry.published = request.form.get('published') or False
            entry.save()

            flash('Entry saved successfully.', 'success')
            if entry.published:
                return redirect(url_for('blog.detail', slug=entry.slug))
            else:
                return redirect(url_for('blog.edit', slug=entry.slug))
        else:
            flash('Title and Content are required.', 'danger')

    return render_template('blog/edit.html', entry=entry)


@blueprint.route('/login/', methods=['GET', 'POST'])
def display_login():
    next_url = request.args.get('next') or request.form.get('next')
    loginstate = False
    from app import login
    loginstate = login()
    print(loginstate)
    if loginstate == True:
        print('login status: ', loginstate)
        return redirect(next_url or url_for('index'))
    else:
        print('login status: ', loginstate)
        return render_template('blog/login.html', next_url=next_url)


@blueprint.route('/logout/', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST':
        session.clear()
        return redirect(url_for('home.index'))
    return render_template('blog/logout.html')

views/capstone_views.py
import flask
import functools

#from app import login
from infrastructure.view_modifiers import response

from flask import (session, redirect, url_for, render_template, request)

blueprint = flask.Blueprint('capstone', __name__, template_folder='templates')


"""@blueprint.route('/login/', methods=['GET', 'POST'])
def display_login():
    next_url = request.args.get('next') or request.form.get('next')
    loginstate = False
    loginstate = login()
    print(loginstate)
    if loginstate == True:
        print('login status: ', loginstate)
        return redirect(next_url or url_for('index'))
    else:
        print('login status: ', loginstate)
        return render_template('shared/login.html', next_url=next_url)"""


def login_required(fn):
    @functools.wraps(fn)
    def inner(*args, **kwargs):
        if session.get('logged_in'):
            return fn(*args, **kwargs)
        return redirect(url_for('blog.display_login', next=request.path))

    return inner


@blueprint.route('/capstone')
@login_required
@response(template_file='capstone/staffingdata.html')
def index():
    return {}


"""@blueprint.route('/logout/', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST':
        session.clear()
        return redirect(url_for('home.index'))
    return render_template('shared/logout.html')"""

views/home_views.py
import flask

from infrastructure.view_modifiers import response

blueprint = flask.Blueprint('home', __name__, template_folder='templates')


@blueprint.route('/')
@response(template_file='home/index.html')
def index():
    return {}


@blueprint.route('/utilities')
@response(template_file='home/utilities.html')
def utilities():
    return {}

templates/blog/create.html
{% extends "shared/_layout.html" %}

{% block title %}New Post{% endblock %}

{% block main_content %}
    <header class="masthead">
        <div class="container d-flex h-25"></div>
        <div class="container flex-fill h-100 align-items-center">
            <form action="{% block form_action %}{{ url_for('blog.create') }}{% endblock %}" class="form-horizontal"
                  method="post">
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="title" name="title" type="text" value="Title">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Content" class="col-sm-2 control-label">Content</label>
                    <div class="col-sm-10">
                        {{ simplemde.css }}
                        {{ simplemde.js }}
                            <textarea class="form-control" id="content" name="content"
                                      style="height: 300px;">Content</textarea>
                        {{ simplemde.load }}
                    </div>
                </div>
                <div class="form-check">
                    <label for="Topics" class="col-sm-2 control-label">Topics</label>
                    <ul class="text-white-50 mb-4 mt-8 mr-4">
                        <li class="list-inline">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> Technology
                                </label>
                            </div>
                        <li class="list-inline">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> Faith
                                </label>
                            </div>
                        <li class="list-inline">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> History
                                </label>
                            </div>
                        <li class="list-inline">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> Personal
                                </label>
                            </div>
                        <li class="list-inline">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> Science
                                </label>
                            </div>
                    </ul>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <input checked="checked" name="published" type="checkbox"
                                           value="y"> Publish?
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-primary" type="submit">{% block save_button %}
                                Create{% endblock %}</button>
                            <a class="btn btn-secondary" href="{{ url_for('blog.blog') }}">Cancel</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </header>


{% endblock %}

templates/blog/edit.html
{% extends "shared/_layout.html" %}

{% block title %}Edit Entry{% endblock %}

{% block main_content %}
    <header class="masthead">
        <div class="container d-flex h-25"></div>
        <div class="container w-auto h-100 align-items-center">
            <form action="{{ url_for('blog.edit', slug=entry.slug) }}" class="form-horizontal" method="post">
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="title" name="title" type="text"
                               value="{{ request.form.get('title', entry.title) }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="Content" class="col-sm-2 control-label">Content</label>
                    <div class="col-sm-10">
                        {{ simplemde.css }}
                        {{ simplemde.js }}
                        <textarea class="form-control" id="content" name="content"
                                  style="height: 300px;">{{ request.form.get('content', entry.content) }}</textarea>
                        {{ simplemde.load }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input {% if entry.published %}checked="checked" {% endif %}name="published" type="checkbox"
                                       value="y"> Published?
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button class="btn btn-primary" type="submit">Save</button>
                        <a class="btn btn-secondary" href="{{ url_for('blog.blog') }}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </header>

{% endblock %}

templates/blog/index.html
{% extends "shared/_layout.html" %}
{% block title %}Blog - Luke Willey{% endblock %}
{% block extra_header %}
    {% if session.logged_in %}
        <li><a class="nav-link js-scroll-trigger" href="{{ url_for('blog.create') }}">New entry</a></li>
    {% endif %}
{% endblock %}
{% block main_content %}

    <!--
    About Section
        <section id="about" class="about-section text-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">Topics</h2>
                        <p class="text-white-50 mb-4">Just pick a topic that interests you for relevant posts. If you're more of
                            a "dealer's choice" type, click <a href="#">here</a> for a random page, or just scroll down for
                            the most recent post. This section is a work in progress.</p>
                        <ul class="text-white-50 mb-4 mt-8 mr-4">
                            <li class="list-inline"><a href="#">Technology</a></li>
                            <li class="list-inline"><a href="#">Faith</a></li>
                            <li class="list-inline"><a href="#">History</a></li>
                            <li class="list-inline"><a href="#">Personal</a></li>
                            <li class="list-inline"><a href="#">Science</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    -->
    <header class="masthead">
        <div class="container d-flex h-100 align-items-center">
            <div class="mx-auto text-center">
                <div class="container">

                    <!-- Project One Row -->
                    <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6">
                            <div class="bg-transparent text-center h-100 project">
                                <div class="d-flex h-100">
                                    <div class="project-text w-100 my-auto text-center text-lg-right">
                                        <h4 class="text-white">Recent Posts</h4>
                                        {% for entry in object_list[:3] %}
                                            <h5 class="text-white"><a href="{% if entry.published %}{{ url_for('blog.detail',
                                    slug=entry.slug) }}{% else %}{{ url_for('edit', slug=entry.slug) }}{% endif %}">
                                                {{ entry.title }}</a>
                                            </h5>
                                            <p class="mb-0 text-white-50">
                                                Posted {{ entry.timestamp.strftime('%m/%d/%Y') }}</p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Project Two Row -->
                    <div class="row justify-content-center no-gutters">
                        <div class="col-lg-6"></div>
                        <div class="col-lg-6 order-lg-first">
                            <div class="bg-transparent text-center h-100 project">
                                <div class="d-flex h-100">
                                    <div class="project-text w-100 my-auto text-center text-lg-left">
                                        <h4 class="text-white">All Posts</h4>
                                        <p class="mb-0 text-white-50">If the most recent posts aren't what your looking
                                            for, check out the <a href="#" >archives</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    {% include "blog/pagination.html" %}

{% endblock %}

templates/blog/login.html
{% extends "shared/_layout.html" %}

{% block title %}Login{% endblock %}

{% block main_content %}
    <header class="masthead">
        <div class="container d-flex h-100 align-items-center">
            <form action="{{ url_for('blog.display_login', next=url_for('blog.blog')) }}" class="form-horizontal"
                  method="post">
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Admin Login</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="password" name="password" type="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button class="btn btn-primary" type="submit">Log in</button>
                    </div>
                </div>
            </form>
        </div>
    </header>
{% endblock %}

templates/blog/logout.html
{% extends "shared/_layout.html" %}

{% block title %}Log Out{% endblock %}

{% block main_content %}
  <p>Click the button below to log out of the site.</p>
  <form action="{{ url_for('blog.logout') }}" class="form-horizontal" method="post">
    <button class="btn btn-primary" type="submit">Log out</button>
  </form>
{% endblock %}

templates/blog/pagination.html
{% if pagination.get_page_count() > 1 %}
<ul class="pager">
  {% if pagination.get_page() > 1 %}
    <li class="previous"><a href="../../infrastructure?{{ request.args|clean_querystring('page', page=pagination.get_page() - 1) }}">&laquo; Previous {{ pagination.get_page() - 1 }} / {{ pagination.get_page_count() }}</a></li>
  {% else %}
    <li class="previous disabled"><a href="#">&laquo; Previous</a></li>
  {% endif %}
  {% if pagination.get_page_count() > pagination.get_page() %}
    <li class="next"><a href="../../infrastructure?{{ request.args|clean_querystring('page', page=pagination.get_page() + 1) }}">Next {{ pagination.get_page() + 1 }} / {{ pagination.get_page_count() }} &raquo;</a></li>
  {% else %}
    <li class="next disabled"><a href="#">Next &raquo;</a></li>
  {% endif %}
</ul>
{% endif %}

templates/blog/post.html
{% extends "shared/_layout.html" %}
{% block title %}{{ entry.title }} - Luke Willey{% endblock %}
{% block extra_header %}
    {% if session.logged_in %}
        <li><a class="nav-link js-scroll-trigger" href="{{ url_for('blog.edit', slug=entry.slug) }}">Edit entry</a></li>
    {% endif %}
{% endblock %}
{% block main_content %}


    <!-- Page Content -->
    <section class="about-section text-center">
        <div class="container text-white">
            <div class="row">
                <!-- Post Content Column -->
                <div class="col-lg-8 text-left">
                    <!-- Title -->
                    <h1 class="mt-4">{{ entry.title }}</h1>
                    <!-- Author -->
                    <p class="lead">
                        by
                        <a>Luke Willey</a>
                    </p>
                    <hr>
                    <!-- Date/Time -->
                    <p>Posted on {{ entry.timestamp.strftime('%m/%d/%Y at %G:%I%p') }}</p>
                    <hr>
                    <!-- Post Content -->
                    {{ entry.html_content }}
                    <hr>

                </div>
                <!-- Sidebar Widgets Column -->
                <div class="col-md-4">
                    <!-- Categories Widget -->
                    <!--<div class="card my-4">
                        <h5 class="card-header text-secondary">Categories</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <a href="#">Web Design</a>
                                        </li>
                                        <li>
                                            <a href="#">HTML</a>
                                        </li>
                                        <li>
                                            <a href="#">Freebies</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <a href="#">JavaScript</a>
                                        </li>
                                        <li>
                                            <a href="#">CSS</a>
                                        </li>
                                        <li>
                                            <a href="#">Tutorials</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>-->
                    <!-- Side Widget -->
                    <div class="card my-4">
                        <h5 class="card-header text-secondary">Links</h5>
                        <div class="card-body">

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
    </section>
    <!-- /.container -->
{% endblock %}

templates/home/utilities.html
{%  extends "shared/_layout.html" %}
{% block title %}Utilities - Luke Willey{% endblock %}
{% block main_content %}

      <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
          <h2 class="text-white-50 mx-auto mt-2 mb-5">You will find some of my development work below. Most of these
          were built with specific tasks in mind, but they are all MIT licensed, so feel free to tweak them as needed
          for your purposes.</h2>
        <a href="https://www.github.com/hansolo580" target="_blank" class="btn btn-primary js-scroll-trigger">Find me on Github</a>
      </div>
    </div>
  </header>

     <section id="projects" class="projects-section bg-light">
        <div class="container">

          <!-- Project One Row -->
          <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
            <div class="col-lg-6">
              <img class="img-fluid" src="/static/img/demo-image-01.jpg" alt="">
            </div>
            <div class="col-lg-6">
              <div class="bg-black text-center h-100 project">
                <div class="d-flex h-100">
                  <div class="project-text w-100 my-auto text-center text-lg-left">
                    <h4 class="text-white">Job Onesheet Generator</h4>
                    <p class="mb-0 text-white-50">Very simple Python 3 program to generate a .docx onesheet for a job
                        based on user input. <br><br> View source on <a href="https://github.com/hansolo580/solid-octo-guacamole"
                                                                    target="_blank">Github</a></p>
                    <hr class="d-none d-lg-block mb-0 ml-0">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

templates/shared/_layout.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/grayscale.min.css" rel="stylesheet">

    {% block additional_css %}{% endblock %}
</head>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">Luke Willey</a>
        <div class="social d-flex justify-content-center">
            <a href="https://www.linkedin.com/in/luke-willey/" target=_blank class="mx-2">
                <i class="fab fa-linkedin js-scroll-trigger"></i>
            </a>
            <a href="https://github.com/hansolo580" target=_blank class="mx-2">
                <i class="fab fa-github js-scroll-trigger"></i>
            </a>
        </div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/#projects">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/utilities">Utilities</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/#signup">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/capstone">Capstone</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/blog">Blog</a>
                </li>
                {% block extra_header %}{% endblock %}
                {% if session.logged_in %}
                    <li>
                        <form action="{{ url_for('blog.logout') }}" class="form-inline" method="post">
                        <button formaction="{{ url_for('blog.logout') }}" class="nav-link js-scroll-trigger bg-transparent border-0" type="submit">Log out</button>
                        </form>
                    </li>
                {% endif %}
                {% if not session.logged_in %}
                    <li>
                        <a class="nav-link js-scroll-trigger" href="{{url_for('blog.display_login')}}" method="post">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="main-content">
    {% block main_content %}{% endblock %}
</div>

<!-- Footer -->
<footer class="bg-black small text-center text-white-50">
    <div class="container">
        Copyright &copy; Luke Willey
        <script>document.write(new Date().getFullYear())</script>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for this template -->
<script src="/static/js/grayscale.min.js"></script>

{% block additional_js %}{% endblock %}

</body>

</html>

templates/shared/login.html
{% extends "shared/_layout.html" %}

{% block title %}Login{% endblock %}

{% block main_content %}
    <header class="masthead">
        <div class="container d-flex h-100 align-items-lg-center">
            <form action="{{ url_for('capstone.display_login', next=url_for('home.index')) }}" class="form-horizontal"
                  method="post">
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Admin Log In</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="password" name="password" type="password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button class="btn btn-primary" type="submit">Log in</button>
                    </div>
                </div>
            </form>
        </div>
    </header>
{% endblock %}

templates/shared/logout.html
{% extends "shared/_layout.html" %}

{% block title %}Log Out{% endblock %}

{% block main_content %}
  <p>Click the button below to log out of the site.</p>
  <form action="{{ url_for('capstone.logout') }}" class="form-horizontal" method="post">
    <button class="btn btn-primary" type="submit">Log out</button>
  </form>
{% endblock %}